### ISSUE TITLE
GBxCart v1.4 Pro Support

### ISSUE THREAD

**Issue by Qiangong2** [KevinVitale/CartBoy#19]
CartBoy says the GBxCart v1.4 Pro is not supported.

**Comment by KevinVitale** [comment]
@Qiangong2 I had to order a v1.4 Pro for myself to test. I plugged it in and it seemed to work just fine with CartBoy.

If you need GBA support, you need to use another reader. I haven't added GBA to CartBoy yet.

<img width="1728" alt="Screen Shot 2022-03-20 at 14 59 35" src="https://user-images.githubusercontent.com/276137/159178243-9d4e3732-12a1-414c-a258-6a8cae744255.png">
