### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by berger2814** [KevinVitale/CartBoy#7]
Hey im very sory to ask but how do I install the app on my mac ?

**Comment by KevinVitale** [comment]
1. Go to the [Releases](https://github.com/KevinVitale/CartBoy/releases) page; and 
2. download the `CartBoy.zip` file for the latest release (click the **Assets** triangle); and
3. Unzip the file on your Mac; and
4. double-click the _CartBoy.app_ to start it.

**Comment by KevinVitale** [comment]
Also, once unzipped, you may need to right-click in the app file (within Finder), and while holding the “Option” key, click “Open”.
